apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gateway-microservice
  labels:
    app: gateway-microservice
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: gateway-microservice
        tier: backend
    spec:
      containers:
      - name: gateway
        image: eu.gcr.io/PROJECT_NAME/gateway-microservice:latest
        ports:
        - name: http-server
          containerPort: 8080
        imagePullPolicy: Always
