apiVersion: v1
kind: Service
metadata:
  name: gateway-microservice
  labels:
    app: gateway-microservice
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: http-server
  selector:
    app: gateway-microservice
